default:
  dora_dir: ./training_weights
  partitions:
    global: debug
    team: debug
  reference_dir: ./
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: ./training_weights
  partitions:
    global: debug
    team: debug
  reference_dir: ./
